Dockerfile
I am starting to try implementing a Dockerfile. This is a starting dockerfile that will be updated to host our application online, but currently it isn't fully setup yet. It shouldn't affect anything on our project yet.
=> Add starting Dockerfile

app.py, templates/_layout.html, templates/about.html, templates/contact.html, templates/forum.html, templates/index.html, templates/login.html, templates/macrotracker.html, templates/signup.html, templates/workouts.html
Added _layout.html, Converted templates, created login and signup
Still need to add
- Login Successful
- Signup Succesful
=> Added _layout.html, Converted templates, created login and signup

Dockerfile
This pull request introduces significant improvements to our Docker setup for local development, aligning with our sprint's goal of enhancing development operations and ensuring a consistent environment across all team members' setups.
We went from a starting file to a now working docker that deploys locally. Next step is pushing this built image to the cloud.
All team members should install Docker (I can show them how if needed) so they can ensure it works on their setup too. 
- Base Image: Switched to python:3.12-slim from ubuntu:20.04 for a more streamlined and Python-focused environment.
- Environment Setup: Removed manual Python installations in favor of the official Python image, simplifying setup and ensuring version consistency.
- Dependency Installation: Used pip install …
=> Added docker support for local development

app.py, templates/macrotracker.html
This is mainly a mockup of the UI, which will likely change as we later implement databases, but the macro tracker form is coming along now. 
This update added an initial implementation of the macro tracker. I added implementation of setting macro goals, and the ability to update your logged calories.
I added app.py logic to accumulate daily macro intake instead of replacing the latest input
Additionally, the macrotracker.html layout has been restructured to display "Today's Macro Goals & Intake" at the top of the page for immediate visibility upon page load. 
WIP: add a error message when trying to implement a blank macro (page will crash if you try to enter a blank field)
=> Updated macrotracker.html and app.py with new features

database/schema.sql
Had to update the name of the User table to troubleshoot database errors...Got it fixed now, just pushing correct name of table to main.
=> Updated schema

requirements.txt
added googlemaps latest ver to requirements.txt
=> Adding googlemaps api to requirements.txt

app.py, templates/_layout.html, templates/profile.html
Made a quick little mockup profile template hardcoded to be replaced by actual database stuff
=> Added placeholder morbius  profile

app.py, templates/workouts.html
**Authentication/sessions ADDED!**
- User can now log in **and log out** of a session (the formatting is something temporary and will be refined later by front-end developers)
- User is unable to access workouts page UNTIL logging in succesfully
- Added appropriate routing/back-end code to support the functionality
=> Shubi database fitness

app.py, templates/secret.html, templates/workouts.html
- Created **secret.html**, which will get more data to populate the database of the user based on who is logged in
- Moved log out button to a different page and removed restricted routing to **workouts.html**
- Added routing/basic back-end code to secret.html
=> Added a secret page and moved the Log out button

app.py, database/fitness_repo.py, static/styles.css, templates/_layout.html, templates/secret.html
Developed **secrets.html** more
- Displayed a way to show the username once logging in to site.
- User can update the users table of the database with their weight. Next PR will have height, Date of Birth, gender, etc.
Added to **app.py**
- Further developed routes in /secret and /submit-question
- Elaborated sessions
- Added light touches to login function
Added to **fitness_repo.py**
- Added a function to determine the username by userID using SQL queries to pull and push data with our local database
=> Added page which allows more storing of data

app.py, database/fitness_repo.py, templates/login.html, templates/secret.html, templates/signup.html
- Updated formatting on **login.html** and **signup.html** to look better
- Updated **secret.html** with POST REQ. form to send user weight, height, DOB, and gender to DB
- Updated **app.py** to handle routing for form
- Updated **fitness_repo.py** to send appropriate data to DB
=> Secret form implementation

app.py, database/fitness_repo.py, templates/_layout.html, templates/login.html, templates/profile.html, templates/secret.html
- Changed layout.html to have Bootstrap implementation (smoother and clean look to interface)
- Added log out button that is conditional (Button will not show if user is logged out)
- Macrotracker, Finder, Profile, and Forum can only be accessed after logging in
- Made big changes to routing of data through log in/log out functions
- Updated submit question to send more data to database
- Profile is accessible after log in and contains database-rendered content (Test it's use by creating an account yourself)
=> Log Out Fully Implemented + Security Measures

app.py, templates/signup.html
- Confirm password field added and implemented properly
-  Flash messaging tweaked for better user experience
=> Minor changes 

app.py, database/fitness_repo.py, templates/profile.html, templates/secret.html, templates/updateprofile.html
On **fitness_repo.py**:
- Updated UpdateUserProfile function to work efficiently
On **app.py**:
- Updated routing to handle UpdateUserProfile page transfer of data
On **templates (secret.html, profile.html, updateprofile.html**:
- Formatting for better user experience
- Created UpdateProfile template to update page whenever user wants to make changes to their profile
=> Update Profile PR

database/schema.sql, templates/about.html, templates/macrotracker.html
- added calories
-  added progress bar
- added different sections for meals (breakfast, lunch, dinner, snacks) with Setting targets on bottom
-formatting on About Us also tweaked/improved
todo: logic implementation (buttons, dynamic updates, etc)
=> Updating About Us/Macro Tracker HTML

app.py, database/workouttracker.py, templates/_layout.html, templates/workouttracker.html
Added very basic and working **workouttracker.html**
Added **workouttracker.py* in databases folder that gets all workouts and allows users to insert new ones
Database updates needed for it to work.
Updated app.py
Updated layout.html to have a profile button AND link to workouttracker
=> Added workout tracker

database/schema.sql
UPDATED SCHEMA TO MORB ON THESE HATERS AHHHHH
=> updated schema AGAIN

Dockerfile, app.py, heroku.yml, macrotracker.py, main.py, supervisord.conf
Adding the heroku.yml and Dockerfile stuff for Heroku cloud testing
=> The Heroku/Docker Update

Dockerfile, app.py
Able to omit unnecessary code and establish a route to Workout Tracker.
So far, it has JavaScript/HTML implementation as well as an external API, all of which works.
Few issues that I will look into and hopefully fix for the next PR.
=> WorkoutTracker route works

app.py, templates/profile.html, templates/workouts.html
Added 2 functions to **workouts.html** 
Added routing in app.py
Added space in profile.html to hold data retrieved from **workouts.html**
=> Trying to implement working star system

templates/secret.html, templates/workouts.html
Maintained Initial State when favoriting an exercise on the workouts page
=> Fixed Favorites
